project:
  type: website
  output-dir: docs
website:
  title: "Carly Caswell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - posts.qmd 

format:
  html:
    theme: 
      light: flatly
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

