project:
  type: website
  output-dir: docs
website:
  title: "Carly Caswell"
  favicon: 2.png
  navbar:
    title: false 
    logo: test.png
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd 
        text: Projects & Blog
      - icon: github 
        href: https://github.com/ccaswell25
      - icon: linkedin
        href: https://www.linkedin.com/in/carlycaswell25/
      - icon: envelope
        href: mailto:ccaswell@bren.ucsb.edu
  page-footer:
    background: light 
    left:
      - "Copyright 2023, Carly Caswell"
format:
  html:
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

